//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimpsharpFsh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GimpsharpFsh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha from image transparency.
        /// </summary>
        internal static string AlphatransText {
            get {
                return ResourceManager.GetString("AlphatransText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtnText {
            get {
                return ResourceManager.GetString("CancelBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed entries are not supported..
        /// </summary>
        internal static string CompressedEntriesNotSupported {
            get {
                return ResourceManager.GetString("CompressedEntriesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory name.
        /// </summary>
        internal static string DirNameText {
            get {
                return ResourceManager.GetString("DirNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXT1.
        /// </summary>
        internal static string DXT1 {
            get {
                return ResourceManager.GetString("DXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXT3.
        /// </summary>
        internal static string DXT3 {
            get {
                return ResourceManager.GetString("DXT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading fsh.
        /// </summary>
        internal static string ErrorLoadingCaption {
            get {
                return ResourceManager.GetString("ErrorLoadingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving fsh.
        /// </summary>
        internal static string ErrorSavingCaption {
            get {
                return ResourceManager.GetString("ErrorSavingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fsh Bitmap.
        /// </summary>
        internal static string FshLayerTitle {
            get {
                return ResourceManager.GetString("FshLayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fsh Type.
        /// </summary>
        internal static string FshtypeText {
            get {
                return ResourceManager.GetString("FshtypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshwrite compression.
        /// </summary>
        internal static string FshWriteText {
            get {
                return ResourceManager.GetString("FshWriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Mipmaps.
        /// </summary>
        internal static string GenMipmaps {
            get {
                return ResourceManager.GetString("GenMipmaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD Base Fsh.
        /// </summary>
        internal static string HDBaseFsh {
            get {
                return ResourceManager.GetString("HDBaseFsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HD Fsh.
        /// </summary>
        internal static string HDFsh {
            get {
                return ResourceManager.GetString("HDFsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is truncated and invalid..
        /// </summary>
        internal static string InvalidFshFile {
            get {
                return ResourceManager.GetString("InvalidFshFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid header was read..
        /// </summary>
        internal static string InvalidFshHeader {
            get {
                return ResourceManager.GetString("InvalidFshHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiscale bitmaps are not supported..
        /// </summary>
        internal static string MultiscaleBitmapsNotSupported {
            get {
                return ResourceManager.GetString("MultiscaleBitmapsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkBtnText {
            get {
                return ResourceManager.GetString("OkBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fsh Save.
        /// </summary>
        internal static string SaveDialogText {
            get {
                return ResourceManager.GetString("SaveDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 24-bit , 32-bit RGBA, DXT1 and DXT3 images are supported..
        /// </summary>
        internal static string UnsupportedFshFormat {
            get {
                return ResourceManager.GetString("UnsupportedFshFormat", resourceCulture);
            }
        }
    }
}
